### ISSUE TITLE
stuff about ssl

### ISSUE THREAD

**Issue by GusCaplan** [seejohnrun/haste-server#133]
i wasn't sure about the best way to get in contact, but i was thinking you guys should get some ssl going @ hastebin.com. I know that cloudflare provides a nice proxy which will add the ssl for you. Sorry if this was a bad place to post this.

**Comment by Logic-gate** [comment]
Hey, 
Don't worry, this is the right place to post. SSL support has been discussed in #82. It something in the works. I am closing this issue due to it being a duplicate. You can check issue #82 for updates on this matter. This is something that may come very soon...not promising anything though. Nevertheless, Thanks.
