### ISSUE TITLE
Security Vulnerabilities

### ISSUE THREAD

**Issue by svavantsa** [seejohnrun/haste-server#157]
Hi,

We at USCIS, scanned this code for security vulnerabilities in the code.

Someone at USCIS made a request to allow them to use this tool. The tool has great functionality. We scanned the code for security vulnerabilities. We feel that if you guys were to fix them, it would be even better and safer to use. See the attached picture. We can provide you with more details upon request.

Is there a way, you guys can look into these and fix them?

![image](https://user-images.githubusercontent.com/4572105/26892878-b63f29ca-4b87-11e7-9f04-a5393b837a7b.png)

**Comment by seejohnrun** [comment]
Thanks for the report

Insecure randomness I'm not too worried about, but I'm interested in more detail on the "vulnerable framework" lines here.  Can you provide some more detail there?

**Comment by Logic-gate** [comment]
@svavantsa _Ping_

**Comment by PassTheMayo** [comment]
*We can provide you with more details upon request.*

6 months later...

**Comment by InnovativeInventor** [comment]
I think I know what triggered the weak cryptographic hash warnings. `md5` is considered insecure. I don't think that md5 is being used in haste-server for any login stuff, so that should be ok. But, in the future, something more secure like SHA-256 or SHA-3 should be used. I'm also interested to hear about the other "vulnerabilities".
