### ISSUE TITLE
Is it possible to enable a recent snippets list in the UI?

### ISSUE THREAD

**Issue by mikedevita** [seejohnrun/haste-server#176]
Often times I am using haste-server to copy "stuff" quickly from one machine to another usually simple stuff, like a product key and such. It'd be awesome if there was a way somewhere in the UI to toggle a list of the last `x` snippets that were created with links to them. 

Much like how https://gist.github.com is linked to your github account and you can see your personal recent gists, but haste-server would be public since there is no auth/user mechanism.

**Comment by seejohnrun** [comment]
This is definitely possible, although bordering on what I would have considered out of scope for this project given how simple hastebin aims to be.  I do like the idea of only showing it when the user requests it though.

Maybe instead of all public posts, since that would be a privacy concern - just a list of the most recent snippets the user has accessed (and by way of that may have created).  Could be stored in localStorage.

**Comment by seejohnrun** [comment]
I'm going to close this for now, I think it's a nice idea but likely more clutter for an interface that aims to stay simple and provide a quick place to dump text
