### ISSUE TITLE
Some issues with highlighting in pascal sources

### ISSUE THREAD

**Issue by vv7v7** [seejohnrun/haste-server#183]
Dear developer,
As you see at the picture below there's some issue with pascal's highlighting:

![screenshot_20171101_135753](https://user-images.githubusercontent.com/25136754/32274076-ea991e84-bf0d-11e7-9224-8e0df22bd8c6.png)

So symbols **''** should be read as one symbol **'** as in the pascal's programming language and not break the string highlighting.

By the way thank you very much as needed for this type of source save place,

Best regards,
vv7v7

**Comment by seejohnrun** [comment]
@vv7v7 We use https://highlightjs.org/ for source highlighting.  Our version on hastebin.com is a little out of date (should be fixed soon), so maybe worth heading over to their demo page to see if this has been fixed.

Otherwise, I'd file an issue over there with a larger snippet of your code, as highlight.js relies on having more information about the code to detect the language correctly.

Thanks!

**Comment by vv7v7** [comment]
Dear seejohnrun,

Thank you for you reply. I'll post an issue on their git.

BEst regards,
vv7v7
