### ISSUE TITLE
Custom URL

### ISSUE THREAD

**Issue by ghost** [seejohnrun/haste-server#207]
When I save, it makes a URL like this:

http://hastebin.com/ateqiwinut

but I would prefer something like

http://hastebin.com/svnpenn1

is it possible

**Comment by seejohnrun** [comment]
Nope currently you'd need to create your own custom server.  I've thought about allowing people to create custom namespaces on hastebin (subdomains) as a premium offering but not sure if people are interested

**Comment by vwbusguy** [comment]
It seems like he is asking for a custom key value rather than a sub-domain - similar to url-shortener services.  For my $.02, since hastebin expires data by default, I don't see much benefit in adding this feature.  In fact, I want to discourage people in my workspace from treating hastebin as though the data will be persistently available.  To be clear, I'm talking of my own deployment and not the hastebin.com offering, but I would be concerned that this feature might communicate an implied availability level for the posted data.
