### ISSUE TITLE
Hastebin.com is down

### ISSUE THREAD

**Issue by stijnb1234** [seejohnrun/haste-server#299]
Hello there!

Hastebin.com is down again. Can you fix it please, because it's handy to use. ;)

Thanks in advance!

Regards,

Stijn

**Comment by MisterFixx** [comment]
Iv'e created a fork of hastebin with slight modifications here and there and it's up and running at https://pastie.io

**Comment by arjvik** [comment]
Someone else seems to have put up [hasteb.in](https://hasteb.in/) as a functional alternative, and it looks almost identical.

**Comment by webmastir** [comment]
> Iv'e created a fork of hastebin with slight modifications here and there and it's up and running at https://pastie.io

Do you have the code for Pastie available on GitHub? I can't seem to find it. 

Your enhancements are really nice. Great job!

**Comment by MisterFixx** [comment]
> > Iv'e created a fork of hastebin with slight modifications here and there and it's up and running at https://pastie.io
> 
> @MisterFixx do you have the code for Pastie available on GitHub? I can't seem to find it.
> 
> Your enhancements are really nice. Great job!

Well i didn't think people would actually care so i didn't bother, but sure, when i have some free time i'll put it up on github.

**Comment by Talv** [comment]
@MisterFixx 

Cool alternative. But one significant feature seems to be missing, specifically `/raw` endpoint:

https://github.com/seejohnrun/haste-server/blob/d922667f56b7acda9599c128405a6546b2425b50/server.js#L112-L116

* https://pastie.io/yytekc.stata
* https://pastie.io/raw/yytekc.stata

Also URLs like https://pastie.io/a/invalid display some incomplete/invalid page instead of returning 404 - not a big deal, but worth mentioning I suppose.

**Comment by MisterFixx** [comment]
@Talv Thank you, i'm fixing this right now.

**Comment by afwn90cj93201nixr2e1re** [comment]
@seejohnrun the general reasons of hastebin is down is - when some one tryna to post too much info on one query, maybe you should just increase nodejs memory or make some limit's? Coz it's really anoying.

**Comment by seejohnrun** [comment]
Thank you / I'm closing a lot of these duplicate issues to get the repo into a reasonable state
