### ISSUE TITLE
Archive this repository and announce abandonment

### ISSUE THREAD

**Issue by birdybro** [seejohnrun/haste-server#340]
I suggest this repo be abandoned officially and archived, since some people are still being misled into using haste-server despite it having multiple known security flaws (see PRs) for months and months.

Thank you.

**Comment by twiclo** [comment]
I should probably mention this fork: https://github.com/zneix/haste-server
zneix has fixed security flaws, added mongodb support, and re-written a lot of the code in node. He also recently pulled in my PR to add support for about 10 more languages including Rust

**Comment by seejohnrun** [comment]
I appreciate the sentiment here, and plan on getting this repository back to active.
Hoping to touch base with @zneix soon

**Comment by zneix** [comment]
Hey, @seejohnrun I would be happy to continue works on haste-server in the proper repository and merge changes from my fork. I wanted to do that some time ago but due to lack of any activity here I decided to continue in my environment.
I see you got back, so I think we can start merging changes. Should I reach out to you via email or some other platform like IRC or Discord to talk about it?
