### ISSUE TITLE
Help: How to setup paste expiration?

### ISSUE THREAD

**Issue by ririko5834** [seejohnrun/haste-server#359]
Hello, i want to setup paste expiration to: pastes will stay for 30 days from their last view

What should i add to `expire` config option?

**Comment by ririko5834** [comment]
I use mongo as storage type

**Comment by OoLunar** [comment]
According to https://github.com/seejohnrun/haste-server#mongodb:
> You can also set an expire option to the number of seconds to expire keys in. This is off by default, but will constantly kick back expirations on each view or post.

From what it sounds like, you have to include the following in your `config.json`:
```json
{
  "type": "mongodb",
  "connectionUrl": "mongodb://localhost:27017/database"
  "expire": 2592000
}
```
What I set in the `expire` field was 2592000 seconds which is 30 days, just as you requested. A reminder that this is from the last view date and not from the creation date.

Lastly, if this issue seems to have solved your problem, please remember to close the issue.

**Comment by ririko5834** [comment]
Thanks
