### ISSUE TITLE
Lots of google for being a self-hosted product

### ISSUE THREAD

**Issue by giuseppeurso** [seejohnrun/haste-server#367]
Hi, I wonder why you used https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js for jquery.
As someone who wants to self host this, I would also like to avoid downloading jquery from google.

Could you let me know wether this sounds reasonable?
Thanks!
G

**Comment by likwidoxigen** [comment]
Hi G,

You can switch from the cdn in a few straightforward steps.
1. Download jquery to `haste-server/static/`
2. Edit `static/index.html` so that it points at your local jquery rather than google.
3. Restart haste-server.

Using a cdn here is helpful to prevent duplication of code and to reduce the small amount of bandwidth serving assets when self hosting. 

All the best, 
Bryce

If this response is helpful to you and resolves your problem please close out this issue. I'm not affiliated with this project but wanted to help out where I could.

**Comment by jonasled** [comment]
Copying jquery directly in the static folder isn't a very good idea, I think it would be better if we include it with npm (https://www.npmjs.com/package/jquery)

**Comment by jonasled** [comment]
I've started a new pull request here: #375

**Comment by giuseppeurso** [comment]
Awesome.

**Comment by giuseppeurso** [comment]
> Hi G,
> 
> You can switch from the cdn in a few straightforward steps.
> 
>     1. Download jquery to `haste-server/static/`
> 
>     2. Edit `static/index.html` so that it points at your local jquery rather than google.
> 
>     3. Restart haste-server.
> 
> 
> Using a cdn here is helpful to prevent duplication of code and to reduce the small amount of bandwidth serving assets when self hosting.
> 
> All the best,
> Bryce
> 
> If this response is helpful to you and resolves your problem please close out this issue. I'm not affiliated with this project but wanted to help out where I could.
