### ISSUE TITLE
Formatting Issues with Specific Syntaxes

### ISSUE THREAD

**Issue by LPGhatguy** [seejohnrun/haste-server#84]
Braces seem to be thrown about with block-defined list initializations in a couple languages (notably Lua).

Take the following block of code:

``` lua
-- Set of 64 0 values
Sets.Zeros = {
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0
}
```

This is automatically given a `.pas` extension and looks like this:
![001267](https://cloud.githubusercontent.com/assets/654598/6422750/f4b564a2-be90-11e4-83c5-bcbc9badca25.png)

If I correct the extension to `.lua`, the output is formatted correctly:
![001268](https://cloud.githubusercontent.com/assets/654598/6422761/14198a62-be91-11e4-84cd-997d90173a7f.png)

Is this a bug?

**Comment by FichteFoll** [comment]
The issue seems to be that multi-line coomments are matched in a single &lt;span&gt; element that spans multiple lines. However, any preceding text in the same "row" as the multi-line span gets aligned on the bottom and not on the top. Here is a screenshot that illustrates the issue:

![2015-02-28_17 35 32](https://cloud.githubusercontent.com/assets/931051/6426908/b2831fb2-bf70-11e4-9d12-c1e1c6cf7b5c.png)


This is also the reason why multi-line comments offset the line numbering because a line in the comment span has a lower height than a normal line in the code block. For some reason there is a `line-height: 1em` override.

**Comment by seejohnrun** [comment]
This has been fixed in a recent version of HLJS it seems / updated now in prod. Thank you!
