### ISSUE TITLE
Add Twitter Cards support

### ISSUE THREAD

**Issue by zet4** [seejohnrun/haste-server#95]
There's a service called "Discord" which is a basically Slack and Team speak had a baby.
Now Discord embeds links if they have any of the standard meta blocks on in their header, like oEmbed or Twitter Cards.

Right now the hastebin links are just not embedding in any way.
Would like to ask to add support for at least one of those standards:
https://dev.twitter.com/cards/types/summary

**Comment by lenovouser** [comment]
:+1:

**Comment by Logic-gate** [comment]
Great idea; However, pastes on haste have a very short lifespan, 30 days in fact. After awhile it will result in dead links, plenty of them across the web. But a great idea nonetheless. I have this setup on my own instance of hastebin because I didnt set up expiration on the pastes, though the title and description are not dynamic. If you are running your own instance, it's very easy to add it.

![screenshot from 2016-08-27 14-57-42](https://cloud.githubusercontent.com/assets/2302251/18027206/a61dcf2a-6c66-11e6-93ba-c94bfda15f3d.png)

Regardless, I'll pass this by the dev.

**Comment by InnovativeInventor** [comment]
@Logic-gate How would I add it? I couldn't find the code in your fork of haste-server.
